consignorbarcodenumber = input("Please scan the consignor barcode number, then hide barcode. Press enter when you are done: ")
print (consignorbarcodenumber)
location = input("Please type the storage location and press enter: ")
print (location)
#getedits 
correctwaist = input("Please type the brand of the garment and press enter: ")
print (correctwaist)
Correction = input ("Waist: 60cm, length: 44cm, do you wish to make any corrections? Type yes or no and press enter: ")
print (Correction)
correctwaist = input("Please type the correct waist measurement in cm and press enter: ")
print (correctwaist)
correctlength = input("Please type the correct length measurement in cm and press enter: ")
print (correctlength)
gettitle = input("Please type the title for this item and press enter: ")
print (gettitle)
gettags = input("Please type the tags, separated by commas, for this item and press enter: ")
print (gettags)
listshopify = input("Do you wish to list this item to Shopify? Type yes or no and press enter: ")
print ("Successfully listed to Shopify, URL is reluv.com.au/admin/products/837228")
startanew = input("Remove the garment and store it. Do you wish to see the listing? Type yes or no and press enter: ")